reloj-checador/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  devise_for :admins, :controllers => { sessions: "admins/sessions",
                                        registrations: "admins/registrations",
                                        passwords: "admins/passwords",
                                        confirmations: "admins/confirmations" }

  resources :companies
  resources :companies
  resources :employees

  resources :attendaces, except: [:edit, :delete]

  get "/welcome", to: "welcome#index"
  get "/checkin", to: "checkins#index"
  get 'reports/att_by_day'
  get 'reports/avg_time_by_employees'
  get 'reports/absence_by_day'
  get 'reports/absence_by_month'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

reloj-checador/app/models/company.rb
class Company < ApplicationRecord
    has_many :employees
    validates :name, :presence => true
    validates :address, :presence => true
end

reloj-checador/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all.order("created_at ASC").paginate(page: params[:page], per_page: 15)
  end

  # GET /companies/1 or /companies/1.json
  def show
    @employees = @company.employees.all.order("employees.created_at ASC").paginate(page: params[:page], per_page: 5)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "Company was successfully created."
      redirect_to companies_url
    else
      flash[:error] = @company.errors.full_messages.join(" and ")
      redirect_to new_company_url(@company)
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    if @company.update(company_params)
      flash[:success] = "Company was successfully updated."
      redirect_to company_url(@company)
    else
      flash[:error] = @company.errors.full_messages.join(" and ")
      render "edit"
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    if @company.employees.count == 0
      if @company.destroy
        flash[:success] = "Company was successfully destroyed."
      else
        flash[:error] = @company.errors.full_messages.join(" and ")
      end
    else
      flash[:error] = "Company has existing employees asociated"
    end
    redirect_to companies_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id]) rescue nil
    companies_redirection if @company.nil?
  end

  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(:name, :address)
  end

  def companies_redirection
    flash[:error] = 'Company does not exist'
    redirect_to companies_url
  end
end

reloj-checador/app/views/companies/_form.html.erb
<%= form_with(model: @company) do |form| %>
  <div class="form-group">
    <%= form.label :name, :class => "form-label" %>
    <%= form.text_field :name, :class => "form-control" + (@company.errors.include?(:name) ? "is-invalid" : "")%>
    <% if @company.errors.include?(:name) %>
      <small class="message-error"><%= @company.errors[:name].join(" ")%></small>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.label :address, :class => "form-label" %>
    <%= form.text_area :address, :class => "form-control" + (@company.errors.include?(:address) ? "is-invalid" : "") %>
    <% if @company.errors.include?(:address) %>
      <small class="message-error"><%= @company.errors[:address].join(" ")%></small>
    <%end%>
  </div>

  <div class="d-flex justify-content-center mt-3 ">
    <%= form.submit :class => "btn btn-primary btn-lg" %>
  </div>
<% end %>

reloj-checador/app/views/companies/edit.html.erb
<div class="container">
  <div class="card p-5">
    <h1 class="card-title text-center">Editing Company</h1>
    <div class="card-body p-5">
      <%= render 'form', company: @company %>
      <%= link_to companies_path, :class => "btn btn-info" do%>
        <i class="fas fa-arrow-left"></i> Back
      <% end %>
      <%= link_to @company, :class => "btn btn-info" do%>
        <i class="fas fa-eye"></i> Show
      <% end %>
    </div>
  </div>
</div>

reloj-checador/app/views/companies/index.html.erb
<div class="container mt-3">
  <h3 class="title">Companies</h3>

  <div class="content">
    <%= link_to 'New Company', new_company_path, :class => "btn btn-primary" %>
    <table class="table table-striped table-responsive mt-4">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr scope="row">
            <td><%= company.name %></td>
            <td><%= company.address %></td>
            <td class="button-td">
              <%= link_to company, :class => "btn btn-success" do %>
                <i class="fas fa-eye"></i>Show 
              <% end %>
              <%= link_to edit_company_path(company), :class => "btn btn-warning" do%>
                <i class="fas fa-user-edit"></i>Edit
              <% end %>
                <%= button_to company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
                <i class="fas fa-trash"></i>Destroy
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="media mb-4">
      <div class="media-body">
        <br>
        <%= will_paginate @companies %>
      </div>
    </div>
  </div>
</div>

reloj-checador/app/views/companies/new.html.erb
<div class="container">
  <div class="card p-5">
    <h1 class="card-title text-center">New Company</h1>
    <div class="card-body p-5">
      <%= render 'form', employee: @company %>
      <%= link_to companies_path, :class => "btn btn-info" do%>
        <i class="fas fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
</div>

reloj-checador/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container card p-4">
  <div class="content">
    <div class="list-group p-4">
      <h2 class="text-center p-4"> General info</h2>
      <p class="list-group-item">
        <strong>Name:</strong>
        <%= @company.name %>
      </p>

      <p class="list-group-item">
        <strong>Address:</strong>
        <%= @company.address %>
      </p>

      <p class="list-group-item">
        <strong>Employees Number:</strong>
        <%= @company.employees.count %>
      </p>

      <div class="table table-responsive">
        <strong>Employees:</strong>
        <table class="table table-striped col-12 col-sm-4 mt-3">
          <thead>
            <tr>
              <th scope="col">Name Lastname</th>
            </tr>
          </thead>
          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td> <a href="<%= employee_path(employee) %>"><%= employee.name %> <%= employee.lastname %></a> </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="media mb-0">
          <div class="media-body">
            <br>
            <%= will_paginate @employees %>
          </div>
        </div>
      </div>      
        
    </div>
  </div>

  <div class="mt-5">
    <%= link_to companies_path, :class => "btn btn-info" do%>
      <i class="fas fa-arrow-left"> </i> Back
    <% end %>
    <%= link_to edit_company_path(@company), :class => "btn btn-info" do%>
      <i class="fas fa-user-edit"></i> Edit
    <% end %>
  </div>
</div>