reloj-checador/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  devise_for :admins, :controllers => { sessions: "admins/sessions",
                                        registrations: "admins/registrations",
                                        passwords: "admins/passwords",
                                        confirmations: "admins/confirmations" }

  resources :companies
  resources :companies
  resources :employees

  resources :attendaces, except: [:edit, :delete]

  get "/welcome", to: "welcome#index"
  get "/checkin", to: "checkins#index"
  get 'reports/att_by_day'
  get 'reports/avg_time_by_employees'
  get 'reports/absence_by_day'
  get 'reports/absence_by_month'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

reloj-checador/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  validates :email, :presence => true
  validates :name, :presence => true
  validates :lastname, :presence => true
  validates :position, :presence => true
  validates :private_number, :presence => true
end

reloj-checador/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all.order(created_at: :desc).group("employees.company_id, id").paginate(page: params[:page], per_page: 15)
    @companies = Company.where(id: @employees.pluck(:company_id).uniq.sort)
  end

  # GET /employees/1 or /employees/1.json
  def show
    @list_attendaces = Employee.select("A.id, A.date, A.time, A.check_type")
                               .joins("JOIN attendaces A ON employees.private_number = A.private_number")
                               .where(private_number: @employee.private_number)
                               .order("A.id DESC")
                               .paginate(page: params[:page], per_page: 15)
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit; end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = "Employee was successfully created."
      redirect_to employees_url
    else
      flash[:error] = @employee.errors.full_messages.join(" and ")
      redirect_to new_employee_url(@employee)
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    if @employee.update(employee_params)
      flash[:success] = "Employee was successfully updated."
      redirect_to employee_url(@employee)
    else
      flash[:error] = @employee.errors.full_messages.join(" and ")
      render 'edit'
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.active = false
    if @employee.save
      flash[:success] = "Employee was successfully inactivated."
    else
      flash[:error] = @employee.errors.full_messages
    end
    redirect_to employees_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id]) rescue nil
    employees_redirection if @employee.nil?
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    params.require(:employee).permit(:email, :name, :lastname, :position, :private_number, :active, :company_id)
  end

  def employees_redirection
    flash[:error] = 'Employee does not exist'
    redirect_to employees_url
  end
end

reloj-checador/app/views/employees/_body_table_attendaces.html.erb
<% @list_attendaces.each do |attendace|%>
  <tr>
    <th scope="row"><%= attendace.id%></th>
    <td><%= attendace.date%> </td>
    <td><%= attendace&.time&.strftime("%H:%M:%S") %> </td>
    <td><%= attendace.check_type%> </td>    
  </tr>
<%end%>

reloj-checador/app/views/employees/_body_table_employees.html.erb
<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.email %></td>
    <td><%= employee.name %></td>
    <td><%= employee.lastname %></td>
    <td><%= employee.position %></td>
    <td><%= employee.private_number %></td>
    <td><%= employee.active %></td>
    <td><%= @companies.select{|com| com.id == employee.company_id}.first.name %></td>
    <td class="button-td">
      <%= link_to employee, :class => "btn btn-success" do %>
        <i class="fas fa-eye"></i>show 
      <% end %>
      <%= link_to edit_employee_path(employee), :class => "btn btn-warning" do%>
        <i class="fas fa-user-edit"></i>Edit
      <% end %>
      <%= button_to employee, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
        <i class="fas fa-trash"></i>Destroy
      <% end %>
    </td>
  </tr>
<% end %>

reloj-checador/app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>

  <div class="form-group">
    <%= form.label :email, :class => "form-label" %>
    <%= form.text_field :email, :class => "form-control " + (employee.errors.include?(:email) ? "is-invalid" : "")%>
    <% if employee.errors.include?(:email) %>
      <small class="message-error"><%= employee.errors[:email].join(" ")%></small>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.label :name, :class => "form-label"%>
    <%= form.text_field :name, :class => "form-control " + (employee.errors.include?(:name) ? "is-invalid" : "") %>
    <% if employee.errors.include?(:name) %>
      <small class="message-error"><%= employee.errors[:name].join(" ")%></small>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.label :lastname, :class => "form-label"%>
    <%= form.text_field :lastname, :class => "form-control " + (employee.errors.include?(:lastname) ? "is-invalid" : "") %>
    <% if employee.errors.include?(:lastname) %>
      <small class="message-error"><%= employee.errors[:lastname].join(" ")%></small>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.label :position, :class => "form-label" %>
    <%= form.text_field :position, :class => "form-control " + (employee.errors.include?(:position) ? "is-invalid" : "") %>
    <% if employee.errors.include?(:position) %>
      <small class="message-error"><%= employee.errors[:position].join(" ")%></small>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.label :private_number, :class => "form-label" %>
    <%= form.number_field :private_number, :class => "form-control " + (employee.errors.include?(:private_number) ? "is-invalid" : "") %>
    <% if employee.errors.include?(:private_number) %>
      <small class="message-error"><%= employee.errors[:private_number].join(" ")%></small>
    <%end%>
  </div>

  <div class="form-group">
    <%= form.label :company, :class => "inputState"%>
    <%= select("employee", "company_id", Company.all.collect {|c| [c.name, c.id]}, {include_blank: "Select a company"},{:class => "form-control"}) %>
  </div>

  <div class="form-check">
    <%= form.check_box :active, :class => "form-check-input" %>
    <%= form.label "employee is active", :class => "form-check-label"%>
  </div>

  <div class="d-flex justify-content-center mt-3 ">
    <%= form.submit :class => "btn btn-primary btn-lg"%>
  </div>
<% end %>

reloj-checador/app/views/employees/edit.html.erb
<div class="container">
  <div class="card p-5">
    <h1 class="card-title text-center">Editing Employee</h1>
    <div class="card-body p-5">
      <%= render 'form', employee: @employee %>
      <%= link_to employees_path, :class => "btn btn-info" do%>
        <i class="fas fa-arrow-left"></i> Back
      <% end %>
      <%= link_to @employee, :class => "btn btn-info" do%>
        <i class="fas fa-eye"></i> Show
      <% end %>
    </div>
  </div>
</div>

reloj-checador/app/views/employees/index.html.erb
<div class="container mt-3">
  <h3 class="title">Employees</h3>
  <div class="content">
    <div class="table-responsive">
      <%= link_to 'New Employee', new_employee_path, :class => "btn btn-primary" %>
      <table class="table table-striped table-responsive mt-4">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">Name</th>
            <th scope="col">Lastname</th>
            <th scope="col">Position</th>
            <th scope="col">Private number</th>
            <th scope="col">Active</th>
            <th scope="col">Company</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody>
          <%= render "body_table_employees", employee: @employee %>
        </tbody>
      </table>
      <div class="media mb-4">
        <div class="media-body">
          <br>
          <%= will_paginate @employees %>
        </div>
      </div>
    </div>
  </div>
</div>

reloj-checador/app/views/employees/new.html.erb
<div class="container">
  <div class="card p-5">
    <h1 class="card-title text-center">New Employee</h1>
    <div class="card-body p-5">
      <%= render 'form', employee: @employee %>
      <%= link_to employees_path, :class => "btn btn-info" do%>
        <i class="fas fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
</div>

reloj-checador/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container card p-4">
  <h1 Class="text-center"> Employee <%= @employee.name %></h1>
  <div class="row">
    <div class="list-group col-sm-12 col-lg-6 p-4">
      <h2 class="text-center"> General info</h3>
      <p class="list-group-item">
        <strong>Email:</strong>
        <%= @employee.email %>
      </p>

      <p class="list-group-item">
        <strong>Name:</strong>
        <%= @employee.name %>
      </p>

      <p class="list-group-item">
        <strong>Lastname:</strong>
        <%= @employee.lastname %>
      </p>

      <p class="list-group-item">
        <strong>Position:</strong>
        <%= @employee.position %>
      </p>

      <p class="list-group-item">
        <strong>Private number:</strong>
        <%= @employee.private_number %>
      </p>

      <p class="list-group-item">
        <strong>Active:</strong>
        <%= @employee.active %>
      </p>

      <p class="list-group-item">
        <strong>Company:</strong>
        <% company = @employee.company %>
        <a href="<%= company_path(company) %>"><%= company.name %></a>
      </p>
    </div>
    <div class="col-sm-12 col-lg-6 p-4">
      <h2 class="text-center"> Attendance </h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Id Attendance</th>
            <th scope="col">Date</th>
            <th scope="col">Time</th>
            <th scope="col">Check Type </th>
          </tr>
        </thead>
        <tbody>
          <%= render "body_table_attendaces", list_attendaces: @list_attendaces %>
        </tbody>
      </table>
      <div class="media mb-4">
        <div class="media-body">
          <br>
          <%= will_paginate @list_attendaces %>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-5">
    <%= link_to employees_path, :class => "btn btn-info" do%>
      <i class="fas fa-arrow-left"> </i> Back
    <% end %>
    <%= link_to edit_employee_path(@employee), :class => "btn btn-info" do%>
      <i class="fas fa-user-edit"></i> Edit
    <% end %>
  </div>
</div>