reloj-checador/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  devise_for :admins, :controllers => { sessions: "admins/sessions",
                                        registrations: "admins/registrations",
                                        passwords: "admins/passwords",
                                        confirmations: "admins/confirmations" }

  resources :companies
  resources :companies
  resources :employees

  resources :attendaces, except: [:edit, :delete]

  get "/welcome", to: "welcome#index"
  get "/checkin", to: "checkins#index"
  get 'reports/att_by_day'
  get 'reports/avg_time_by_employees'
  get 'reports/absence_by_day'
  get 'reports/absence_by_month'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

reloj-checador/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= welcome_path %>">CHECADOR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item" id="attendaces_li">
                <a class="nav-link" href="<%= attendaces_path %>">ATTENDACES</a>
            </li>            
            <li class="nav-item" id="companies_li">
                <a class="nav-link" href="<%= companies_path %>">COMPANIES <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item" id="employees_li">
                <a class="nav-link" href="<%= employees_path %>">EMPLOYEES</a>
            </li>
            <li class="nav-item dropdown" id="reports_li">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                REPORTS
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="<%= reports_att_by_day_path %>">Attendance by day</a>
                <a class="dropdown-item" href="<%= reports_avg_time_by_employees_path %>">Average time employees checked in/out by month</a>
                <a class="dropdown-item" href="<%= reports_absence_by_day_path %>">Absence report by day</a>
                <a class="dropdown-item" href="<%= reports_absence_by_month_path %>">Absence report by month</a>
                </div>
            </li>
        </ul>

        <ul class="navbar-nav mr-md-1">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_admin&.name %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<%= edit_admin_registration_path %>">Edit Profile</a>
                    <%= button_to "Log Out", destroy_admin_session_path, method: :delete, class: "dropdown-item"%>
                </div>
            </li>
        </ul>
    </div>
</nav>

<div style="display: none">
    <input type="hidden" readonly="true" value="<%= controller.controller_name %>" id="controller_name">
</div>
<%= javascript_pack_tag 'layouts/navbar' %>

reloj-checador/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelojChecador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>
    <%= flash_msg %>
    <%= yield %>
  </body>
</html>

reloj-checador/app/views/layouts/checkin.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelojChecador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>
    <%= flash_msg %>
    <%= yield %>
    
  </body>
</html>

reloj-checador/app/views/layouts/main_check.html.erb
<button type="button" class="btn btn-light" href="<%= new_admin_session_path %>">Iniciar Session</button>